### PR TITLE
feat: support filtering by security releases via ?security=true

### LINKED ISSUE #5: proposal: support limiting results to security releases
Back in May, the node.js Releases team added a new `security` property to the index (https://github.com/nodejs/nodejs-dist-indexer/pull/9).

The property is a boolean that indicates if the release is a security release, which is useful for a few reasons (many described in https://github.com/nodejs/Release/issues/437#issue-435787538); the one that I believe justifies adding functionality to `resolve-node` is this one (emphasis mine):
> Theoretically, developers (us included!) could use this in a few ways:
> ...
> - loop over every release in a release line until they encounter true – when they encounter true for the first time, they **know that version is the minimum secure version**

The proposal is to add support for a `security` query param on all endpoints that causes the eligible list of versions to be filtered by `security === true` before applying the `maxSatisfying()` query.

eg:
```sh
$ curl https://resolve-node.now.sh/lts/dubnium
v10.17.0

$ curl https://resolve-node.now.sh/lts/dubnium?security=true
v10.16.3
```

This tells us that, at the time of the query, anyone running Dubnium < `10.16.3` is on a known, potentially insecure version.

what do y'all think? should I whip together a PR?

### PR DESCRIPTION
**Pull request by knksmith57**
Resolves #5

### CODE REVIEW

**Comment by knksmith57** [comment]
heads up @TooTallNate, here's another proposed feature whenever you have a chance to take a look :smile:

**Comment by knksmith57** [comment]
heya @TooTallNate; any chance y'all could take a pass at this one? I think this adds notable value to the API. Thanks!

**Comment by TooTallNate** [comment]
Hey @knksmith57, sorry for missing this one. Changes look good to me, thank you for the useful feature!

**Comment by knksmith57** [comment]
awesome, thanks for landing!

**Comment by knksmith57** [comment]
looks good!

```sh
❯ curl -s 'https://nodejs.org/dist/index.json' | jq -r '.[]|[.version,.security]|@tsv' | head -5
v14.13.0	false
v14.12.0	false
v14.11.0	true
v14.10.1	false
v14.10.0	false

❯ curl -L resolve-node.now.sh/14
v14.13.0

❯ curl -L resolve-node.now.sh/14?security=true
v14.11.0
```

**Pull request merged**
